### ISSUE TITLE
Dont able to drag outside of view in view

### ISSUE THREAD

**Issue by ZalakSA** [KevinZhouRafael/DragDropiOS#4]
Hello Support team,

I am building app having collection view inside another collection view and dragging view of the innermost cell to another view top of all views. But cannot drag view outside its foremost superview. 

Let me describe my view hierarchy:-

```
Main view controller -> Having 2 views 
1) 1st view where I wanted to drop by data
2) 2nd view having collection view and inside it there is another collectionview and I have assigned class "**DragDropcollectionview**" to it. I wanted to drag view from innermost collection viewcell to @1st view i.e. Outside of all.
```

But not able to drag it.
How can I make it draggable outside of all its superview ?

Thanks,

**Comment by KevinZhouRafael** [comment]
Hello ZalakSA:
1、Please make sure the canvas of DragDropManager is both draggable views and droppable views' superview in the view hierarchy.
2、Make sure the collectionview that drag out of  implements  DragDropCollectionViewDelegate correctly.
It should be run.

**Comment by ZalakSA** [comment]
Hello KevinZhouRafael  

I tried to give the delegate to its superview as well but still not moving out.
One more thing I found today is When I try to drag droppable view named "**view1**" to the cell it was not moving but when once a cell is dragged to view, then view starts moving but not before than that.

I kept two views and try to drag the image in each other but it was not working.
I want to drag the image from one view to another view.

Please guide me to achieve it.

Thanks,

**Comment by ZalakSA** [comment]
Hello KevinZhouRafael

For reference I have created one image showing design, I wanted to work with drag drop.

![screen shot 2017-10-31 at 10 25 22 am](https://user-images.githubusercontent.com/14737021/32208050-01450582-be26-11e7-93c7-f99cbed3ead6.png)

I want to drag innermost view to dragdrop view with white background kept at the top. But I am not able to drag outside of dragdrop collectionview that is inner one. I have given drag drop collectionview class to both collection view.

Please guide me for this.

Thanks,
Zalak

**Comment by KevinZhouRafael** [comment]
Please set drag drop collectionview class only to Dragdropcollectionview.
Don't set it to Dragdropcollectionview1.


2017-10-31 12:58 GMT+08:00 ZalakSA <notifications@github.com>:
