### ISSUE TITLE
Ghosting

### ISSUE THREAD

**Issue by Tr736** [KevinZhouRafael/DragDropiOS#5]
every now and again the drag function stops without calling the delegate and a uiimage representation remains on the screen thus causing a ghosting effect.

im dragging one cell from collection view a to collection view b

**Comment by Tr736** [comment]
found how its occuring

if you are in the middle of a drag and the collection view reload then the ghosting appears

for now I have added a tag to the image view  that upon drop completes I remove the view and I prevent the collection view from reloading while im in the dragging state using a boolean

**Comment by KevinZhouRafael** [comment]
Thank you for your feedback.
I add cancel dragging progress feature on 0.2.1 version.
Please use DragDropiOS.cancelDragging() before  reloadData.

we useually reloadData in stopDragging() or stopDropping().,and use reloadSection, insert etc. So I don't let it cancel dragging when reloadData automatic.
