### ISSUE TITLE
How to  drop with existing content 

### ISSUE THREAD

**Issue by kirti301290** [KevinZhouRafael/DragDropiOS#6]
hi
this control working fine but facing one problem how to drop which already dropped content
want to overdrop functinality like move one by one  image  to folder
thanks

**Comment by KevinZhouRafael** [comment]
It is easy。Just override function

func tableView(_ tableView: UITableView, canDropWithDragInfo dataItem: AnyObject, AtIndexPath indexPath: IndexPath) -> Bool ；

Return true in any case you want。
