### ISSUE TITLE
performing a segue while dragging -> draggable element freezes on screen

### ISSUE THREAD

**Issue by peakerest** [KevinZhouRafael/DragDropiOS#7]

**Comment by KevinZhouRafael** [comment]
Please use DragDropiOS.cancelDragging() before perform a segue.

**Comment by peakerest** [comment]
I`ve already tried it with DragDropiOS.cancelDragging(). 
But the problem remains.

**Comment by peakerest** [comment]
the same happens when you drag one element in your example application and before dropping, clicking another draggable element. Hope you can help

**Comment by peakerest** [comment]
seems we only have to delete the represtationImageView from the old bundle before assign the new one. Otherwise we are not able to remove the old represtationImageView from the superview since we've lost the reference

DragDropManager: #106
`   if let bundle = self.bundle{
       bundle.representationImageView.removeFromSuperview()
    }
`

**Comment by KevinZhouRafael** [comment]
I fix this bug on 0.2.3 version.
Only one dragging progress be allowed at the same time. The new dragging progress will be fails, and the repressentationImageView would not shows.
